### ISSUE TITLE
Extract rendering code to a dedicated library

### ISSUE THREAD

**Issue by vinnydiehl** [wildfiler/drtiled#17]
I have a bare bones proof-of-concept for a renderer with a camera:

https://user-images.githubusercontent.com/1045694/235298317-224892e1-3867-4c18-aa95-d5c381f5eb27.mp4

[Here](https://gist.github.com/vinnydiehl/d8bf2ab4cb303eb434ad666190fc8e03) is what I have so far; an API to render any or all of the tile layers, any or all of the object layers, and a method to render any primitive relative to the map (with camera offset applied).

Right now the camera is just ticking over a sine wave, but working on methods to ease to player position. This will be better organized once I get my thoughts together.

This library would eliminate `ObjectLayer#render_debug` from drtiled, but I haven't started ripping anything else out yet. What else were you thinking?

**Comment by vinnydiehl** [comment]
First glimpse of a rendering library: https://github.com/vinnydiehl/drtiled-renderer

Still quite basic and very much prone to restructuring as I figure out the best way to build games around this map editor. Things like easing are yet to come. Still, it's something you can drop into a project right now alongside this library and get a lot of functionality with surprisingly little code- give the [sample app](https://github.com/vinnydiehl/drtiled-renderer/blob/main/app/platformer.rb) a run when you get the time (noting that it depends on #23 :wink:).

I'd say this makes `ObjectLayer#render` redundant. I can start a PR to remove it and link out in the README- unless you want to maintain it in here too? Let me know.

Cheers! :beers: 

https://user-images.githubusercontent.com/1045694/235765463-0e5b425d-cfa9-476f-a40c-564c8ec4c005.mp4

**Comment by wildfiler** [comment]
Wow, impressive work :)

I think if supporting render 'as it is' in this library is not too costly, then there is no need to remove it for now. It helps to verify if the new code in the library at least works. I have a plan to move samples to another repo in the future, then we can remove render-related code from the lib and will link to sample apps from other devs if they don't mind.

Hope this will not affect developing a separate render library :)

Later this month I will release 0.2 version with all your changes, and will try to think about releasing process because if another library will depend on this it will be a pain to maintain correct versions of both libraries in games.

Feel free to add link to your repo in readme, I think this can be helpful for new devs.

Sorry, I'm a little bit busy right now, I'm in the process of moving to another country, so not responding in case if response needs deep thought :(

**Comment by vinnydiehl** [comment]
Yeah, that's fine! I still haven't found a good solution to keeping dev environments synced, between my fork of this library, the copy of it that I have in my sandbox environment, and the *other* copy that I now have in my dependent library, I'm going to have to do something. :sweat_smile: Anyway, keeping one function synced is no big deal.

Release process is up to you. I've used flow, I've done nightly trunk releases, I don't see anything wrong with either of them. The slower, timestamped, changelogged releases that flow affords might suit this type of thing better. Once this is feature-complete we could call it 1.0 and sync versions, and of course, [semantic versioning](https://semver.org/) so there would never be a question about breaking changes. We'll just say that breaking changes before 1.0 don't count. :stuck_out_tongue:

**Comment by wildfiler** [comment]
Yeah, semver before 1.0.0 is not semver, we are free to do whatever we want :D
