### ISSUE TITLE
Feature Request: Tiled::Text class

### ISSUE THREAD

**Issue by GryphonClaw** [wildfiler/drtiled#52]
As the title says, I would like to see a Tiled::Text class that encapsulates the text xml like Tiled::Color does.

It would be easy to make a function on it to translate it to a DR label "to_hash" perhaps?

**Comment by wildfiler** [comment]
Done in #53

I added `to_h` method for `Tiled::MapObject::Text` object, it looks appropriate because I can't think of representing it as a hash other than a primitive hash.

But it doesn't work with custom fonts, you will need to add font to resulting hash. I'll try to think a way to map tiled fonts to fonts from DR, but for now default font will be used, or you can override it in your code.
